const SketchThumbnailArray = [
  "Ant",
  "Badger",
  "Bear",
  "Beaver",
  "Bird",
  "Bug",
  "Bull",
  "Bumblebee",
  "Butterfly",
  "Cat",
  "Caterpillar",
  "Chicken",
  "Clown Fish",
  "Corgi",
  "Cow",
  "Crab",
  "Deer",
  "Dinosaur",
  "Dog",
  "Dolphin",
  "Dragonfly",
  "Duck",
  "Elephant",
  "Falcon",
  "Fish",
  "Fly",
  "Frog",
  "Giraffe",
  "Gorilla",
  "Grasshopper",
  "Horse",
  "Hummingbird",
  "Insect",
  "Kangaroo",
  "Kiwi Bird",
  "Ladybird",
  "Leopard",
  "Lion",
  "Llama",
  "Mite",
  "Mosquito",
  "Octopus",
  "Panda",
  "Prawn",
  "Puffin Bird",
  "Rabbit",
  "Rhinoceros",
  "Seahorse",
  "Shark",
  "Sheep",
  "Snail",
  "Spider",
  "Starfish",
  "Stork",
  "Turtle",
  "Unicorn",
  "Whale",
  "Wolf",
];

const LanguageDropdownValues = [
  { display: "Python", value: "python" },
  { display: "Processing", value: "processing" },
  { display: "HTML", value: "html" },
];

const LanguageDropdownDefault = { display: "Python", value: "python" };
const SORT_BY_NAME = 0;
const SORT_BY_CREATE = 1;
const SORT_BY_UPDATE = 2;
module.exports = {
  SketchThumbnailArray,
  LanguageDropdownValues,
  LanguageDropdownDefault,
  SORT_BY_NAME,
  SORT_BY_CREATE,
  SORT_BY_UPDATE
};
